export const RESTROOM_MARKERS_LOADED = 'RESTROOMS_MARKERS_LOADED';
export const MAP_CENTER_CHANGE = 'MAP_CENTER_CHANGE';

export const MARKER_ATTRIBUTES_SET = 'MARKER_ATTRIBUTES_SET';
export const MARKER_IMAGES_SET = 'MARKER_IMAGES_SET';

export const RESTROOM_MARKER_ADDED = 'RESTROOM_MARKER_ADDED'