export const RESTROOM_MARKERS_LOADED = 'RESTROOMS_MARKERS_LOADED';
export const MAP_CENTER_CHANGE = 'MAP_CENTER_CHANGE';

export const MARKER_ATTRIBUTES_SET = 'MARKER_ATTRIBUTES_SET';
export const MARKER_IMAGES_SET = 'MARKET_IMAGES_SET';
