export const RESTROOM_MARKERS_LOADED = 'RESTROOM_MARKERS_LOADED';
export const MAP_CENTER_CHANGE = 'MAP_CENTER_CHANGE';

export const MARKER_ATTRIBUTES_SET = 'MARKER_ATTRIBUTES_SET';
export const MARKER_IMAGES_SET = 'MARKER_IMAGES_SET';
export const RESTROOM_MARKER_ADDED = 'RESTROOM_MARKER_ADDED';

export const RESTROOM_REVIEW_STARS_CHANGED = 'RESTROOM_REVIEW_STARS_CHANGED';
export const RESTROOM_REVIEW_IMAGE_UPLOADED = 'RESTROOM_REVIEW_IMAGE_UPLOADED';
export const RESTROOM_REVIEW_IMAGE_REMOVED = 'RESTROOM_REVIEW_IMAGE_REMOVED';
export const RESTROOM_REVIEW_CLEAR = 'RESTROOM_REVIEW_CLEAR';
