export const USER_LOCATION_GRANTED = 'USER_LOCATION_GRANTED';
export const USER_LOCATION_DENIED = 'USER_LOCATION_DENIED';
export const USER_LOCATION_ERROR = 'USER_LOCATION_ERROR';

export const RESTROOMS_LOADED = 'RESTROOMS_LOADED';
