export const USER_LOCATION_GRANTED = 'USER_LOCATION_GRANTED';
export const USER_LOCATION_DENIED = 'USER_LOCATION_DENIED';
export const USER_LOCATION_ERROR = 'USER_LOCATION_ERROR';

export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';
export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
export const USER_LOGOUT_FAIL = 'USER_LOGOUT_FAIL';

export const USER_FAVORITES_LOADED = 'USER_FAVORITES_LOADED';
export const USER_FAVORITE_ADDED = 'USER_FAVORITE_ADDED';
export const USER_FAVORITE_REMOVED = 'USER_FAVORITE_REMOVED';
export const RESTROOM_MARKER_FAVORITED = 'RESTROOM_MARKER_FAVORITED';
export const RESTROOM_MARKER_UNFAVORITED = 'RESTROOM_MARKER_UNFAVORITED';
export const USER_VISITED_RESTROOMS_LOADED = 'USER_VISITED_RESTROOMS_LOADED';
export const USER_VISITED_ADDED = 'USER_VISITED_ADDED';
export const USER_VISITED_REMOVED = 'USER_VISITED_REMOVED';
export const USER_VISITED_CLEAR = 'USER_VISITED_CLEAR';
export const RESTROOM_MARKER_VISITED = 'RESTROOM_MARKER_VISITED';
export const RESTROOM_MARKER_UNVISITED = 'RESTROOM_MARKER_UNVISITED';

export const USER_FEED_STATE_CHANGED = 'USER_FEED_STATE_CHANGED';
export const USER_FEED_STATE_CLEARED = 'USER_FEED_STATE_CLEARED';
