export const USER_LOCATION_GRANTED = 'USER_LOCATION_GRANTED';
export const USER_LOCATION_DENIED = 'USER_LOCATION_DENIED';
export const USER_LOCATION_ERROR = 'USER_LOCATION_ERROR';

export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';

export const USER_FAVORITES_LOADED = 'USER_FAVORITES_LOADED';
export const USER_FAVORITE_ADDED = 'USER_FAVORITE_ADDED';
export const USER_FAVORITE_REMOVED = 'USER_FAVORITE_REMOVED';
export const RESTROOM_MARKER_FAVORITED = 'RESTROOM_MARKER_FAVORITED';
export const RESTROOM_MARKER_UNFAVORITED = 'RESTROOM_MARKER_UNFAVORITED';
